# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: cvt

on:
   workflow_call:
      secrets: 
           PLATFORM_ACTIONS_TOKEN :
                              description: ""
                              required: true   

jobs:
  build:

    runs-on: [self-hosted]

    steps:
    - uses: actions/checkout@v3
      with : 
           repository: Arun-Platform/Travel
           token     : ${{ secrets.PLATFORM_ACTIONS_TOKEN }}
           path      : Travel
   
    #INstall Node on the runner
    - name: Install Node
      uses: actions/setup-node@v1
      with:
          node-version: "12.x"


      # Install the newman command line utility and also install the html extra reporter
    - name: Install newman
      run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
      shell: cmd
      
        # Run the POSTMAN collection
    - name: Run POSTMAN collection
      run: |
          newman run ./Travel/TestAPi.postman_collection.json -e ./Travel/Environment.postman_environment.json
      shell: cmd
