name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: [self-hosted]

    steps:
    - uses: actions/checkout@v3 
       
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
    - name: Restore Packages
      run: nuget restore Travel.sln
      shell: cmd
      working-directory: ./Travel
       
    - name: Build Solution
      shell: cmd
      run: |
          msbuild.exe Travel.sln /p:platform="Any CPU" /p:configuration="Release"
      working-directory: ./Travel
      
    - name: Deploy to IIS
      shell: cmd
      run: |
        xcopy /s /y .\Travel\* D:\publishdata
