name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: [self-hosted]

    steps:
    - uses: actions/checkout@v3 
       
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    - run: |
          $path = "C:\BussinessAPI"
          If(!(test-path -PathType container $path))
          {
                New-Item -ItemType Directory -Path $path
                Start-IISCommitDelay
                $TestSite = New-IISSite -Name BussinessAPI -BindingInformation "*:8121:" -PhysicalPath "C:\BussinessAPI" -Passthru
                $TestSite.Applications["/"].ApplicationPoolName = "DefaultAppPool"
                Stop-IISCommitDelay
          }
      shell: cmd  

    

