name: .NET Create Site
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:
  create-iis-site:
   runs-on: [self-hosted]
   env:
      server: 'iis-server.domain.com'
      website-name: 'Default Website'
      apo-pool-name: 'DefaultAppPool'
      website-host-header: '*.defaultsite.com'
      website-path: 'c:\inetpub\wwwroot'

   steps:
      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
        shell: cmd
