name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

   runs-on: [self-hosted]

   steps: # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      
    - name: Restore Packages
      run: nuget restore Travel.sln
      shell: cmd
      working-directory: ./Travel
       
    - name: Build Solution
      shell: cmd
      run: |
          msbuild.exe Travel.sln /p:platform="Any CPU" /p:configuration="Release"
      working-directory: ./Travel
      
    - name: Deploy to IIS
      run: |
        iisreset /stop
        xcopy /s /y .\Travel\* D:\publishdata
        iisreset /start        
      shell: cmd
        
     #INstall Node on the runner
    - name: Install Node
      uses: actions/setup-node@v1
      with:
          node-version: "12.x"


      # Install the newman command line utility and also install the html extra reporter
    - name: Install newman
      run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
      shell: cmd

      # Make directory to upload the test results
    - name: Make Directory for results
      run: mkdir -p testResults
      shell: cmd 


      # Run the POSTMAN collection
    - name: Run POSTMAN collection
      run: |
          newman run ./Travel/TestAPi.postman_collection.json
      shell: cmd

