name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: [self-hosted]

    steps:
   
    - name: setexe
      shell: cmd
      run: |
       Powershell Set-ExecutionPolicy -Scope CurrentUser -ExecutionPolicy Unrestricte -Force
       
    - name: Setup MSBuild 
      run : |
          powershell.exe -File C:\actions-runner\_work\Travel\Travel\test.ps1
      

    

