name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: [self-hosted]

    steps:
   
    - name: setexe
      shell: cmd
      run: |
       Powershell Set-ExecutionPolicy -Scope CurrentUser -ExecutionPolicy Unrestricte -Force
       
    - name: Setup MSBuild
      shell: cmd
      run  : .\Powershell\test.ps1    

    

