name: .NET Create Site
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:
  create-iis-site:
   runs-on: [self-hosted]
   env:
      server: 'iis-server.domain.com'
      website-name: 'Default Website'
      apo-pool-name: 'DefaultAppPool'
      website-host-header: '*.defaultsite.com'
      website-path: 'c:\inetpub\wwwroot'

   steps:
    - name: exe
      shell: cmd
      run: |
        powershell Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass
        
    - name: Create Web Site 
      uses: im-open/iis-site-create@v3.0.2    
          
    - name: exe
      shell: cmd
      run: |
        powershell Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass
