name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

   runs-on: [self-hosted]

   steps: # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3
      
    - name: Deploy to IIS
      shell: cmd
      run: |
        iisreset /stop
        xcopy /s /y .\Travel\* D:\publishdata
        iisreset /start    
