name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: [self-hosted]

    steps:
    - uses: actions/checkout@v3 
    - name: setexe
      shell: cmd
      run: |
       Powershell Set-ExecutionPolicy -Scope CurrentUser-ExecutionPolicy Unrestricte -Force
       
    - name: Setup MSBuild
      run  : .\Test.ps1    

    

