name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: [self-hosted]    
        
  ExecuteCVT:
    
    name: Trigger CVT
    needs: [build]
    uses: ./.github/workflows/cvt.yml
    secrets :
          PLATFORM_ACTIONS_TOKEN  : ${{ secrets.PLATFORM_ACTIONS_TOKEN }}
    
         
